### ISSUE TITLE
Unable to overide action for the owasp managed rules

### ISSUE THREAD

**Issue by Sevenn83** [cloudflare/terraform-provider-cloudflare#2056]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.27.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id     = "zoneId"
  name        = "managed WAF"
  description = "managed WAF ruleset description"
  kind        = "zone"
  phase       = "http_request_firewall_managed"

  rules {
    action = "execute"
    action_parameters {
      id = "4814384a9e5d4991b9815dcfc25d2f1f"
      overrides {
        action = "log"
      }
    }
    expression  = "true"
    description = "Cloudflare's implementation of the Open Web Application Security Project (OWASP) ModSecurity Core Rule Set."
    enabled     = true
  }
}
```

### Link to debug output

N/A

### Expected output

OWASP action should be set to true
<img width="555" alt="H3UyUKoC2022-11-24@2x" src="https://user-images.githubusercontent.com/8145934/203796449-3b0b876f-0c0c-4eac-8f5a-01014fff9378.png">

### Actual output

OWASP Action is not set to log

<img width="559" alt="1oxHc0x22022-11-24@2x" src="https://user-images.githubusercontent.com/8145934/203796361-fc4104d0-4c79-4887-9eec-fb23c4a26d51.png">

### Steps to reproduce

1. use the cloudflare_ruleset as this issue
2. tf plan && tf apply
3. Check on the gui

### Additional factoids

The action overide is not working for this set of managed rule (no problem for other managed rules), but there is also no parameter to change the anomaly score nor the paranoia level.

**Comment by jacobbednarz** [comment]
this doesn't appear to be a bug in terraform but a service issue that was resolved earlier today - https://www.cloudflarestatus.com/incidents/2fnrp5hl209r. can you please try again? we have test coverage for overriding these actions so it would be highly unlikely this is broken now from the terraform side.

in future, please help us help you by filling out all the required issue template fields including the debug output. otherwise, as the automation mentioned, it is unlikely to get looked at as there isn't enough information to go on.

**Comment by Sevenn83** [comment]
I've edited the original post with debug link.
The problem still here, I still think it's a problem with the provider, not the service.

I'm unable to overide "action" for the OWASP managed rule, also, the provider don't have anything for the paranoia level nor anomaly score

I think you should reopen this ticket @jacobbednarz

**Comment by jacobbednarz** [comment]
> The problem still here, I still think it's a problem with the provider, not the service.

i've gone over your example again (using the debug log) and it's not working because you're not including the ID in the override. you can see a full working example at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/resource_cloudflare_ruleset_test.go#L1960. without an ID, you're telling the action to be log but it's not targeting anything.

> the provider don't have anything for the paranoia level nor anomaly score

setting the paranoia level and anomaly score are both supported in the provider. you can see a test case for this at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/resource_cloudflare_ruleset_test.go#L1929-L1972. documentation is at https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#nestedblock--rules--action_parameters--overrides--categories and https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#score_threshold

**Comment by Sevenn83** [comment]
Amazing it's work, thank you for you time and help.
