### ISSUE TITLE
data.cloudflare_account takes SIGNIFICANTLY longer in v5 than v4

### ISSUE THREAD

**Issue by dlacosteGFM** [cloudflare/terraform-provider-cloudflare#5298]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

I use this format to initialize a variable for my account_id, as it's used in almost every resource type:

```
data "cloudflare_accounts" "self" {
  name = "Example, Inc."
}

locals {
  cloudflare_account_id = data.cloudflare_accounts.self.accounts[0].id
}
```

In v4 this returns (effectively) instantly.

In v5:
```
data.cloudflare_accounts.self: Reading...
...
data.cloudflare_accounts.self: Read complete after 3m31s [name=Example, Inc.]
```

(No, I am not getting rate limited: reverting to v4 continues to be instant, and all later calls in this terraform run are effectively instant as well.  Using curl is also instant)

### Affected resource(s)

data.cloudflare_accounts

### Terraform configuration files

```hcl
terraform {
  required_version = ">= 1.9.8, < 1.10"
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 5.1"
    }
  }
}

provider "cloudflare" {
  api_token = "SECRET_VALUE"
}

data "cloudflare_accounts" "self" {
  name = "Example, Inc."
}

locals {
  cloudflare_account_id = data.cloudflare_accounts.self.result[0].id
}

output "account_id" {
  value = local.cloudflare_account_id
}
```

### Link to debug output

[Gist](https://gist.github.com/dlacosteGFM/3e250df7ce93e3a4d4ad185c72f9dbf5)

### Panic output

N/A

### Expected output

Not have to wait more than 3 minutes to get an account ID

### Actual output

I waited more than 3 minutes to get an account ID

### Steps to reproduce

1. Take the provided minimal terraform code
2. Run it
3. Observe result

**Comment by jacobbednarz** [comment]
on my test account, the data source takes < 2s to fetch with just under 100 zones. 

this looks to be a local issue so i'd recommend investigating the size of your state file and number of dependencies calling this resource (which will make the dependency walking slow) or getting rate limited by the API which will automatically get retried internally to the provider.

**Comment by dlacosteGFM** [comment]
I am more than willing to believe there is something I need to have configured in particular way, but this is the `data.cloudflare_accounts` object, not `data.cloudflare_zones` : there are no zones returned in the result.

I know it's not rate limiting.  When it's rate limited you get a 429 response from curl (I _have_ gotten the 429 at different times and would not open the ticket for rate limiting, this is a different occurrence and cause).

You can also see the complete content of the terraform: I have reduced this to a minimum terraform file: one single main.tf with nothing else, in a brand new (local, not even remote) statefile, so it's not the number of dependencies either, as there are none.  This entire terraform block just looks up data.cloudflare_accounts, filtering on one account name, and prints it as an output.  That is it, there is nothing else.

Here is a script I ran to demonstrate this.  As you can see there is a before and after all running quickly, it is _only_ the v5 provider that has an issue:

```
source time-comparison
Tue Mar 11 15:10:17 PDT 2025
Running curl:
curl -s -X GET -H  -H "Content-Type:application/json"  -o /dev/null  0.02s user 0.02s system 13% cpu 0.265 total
Tue Mar 11 15:10:18 PDT 2025
Checking cloudflare terraform plugin version:
    cloudflare = {
      source = "cloudflare/cloudflare"
      # 5.0 renames a bunch of things, major upgrade:
      version = "~> 5.1"
15:10:18.311 INFO Reading version from Terraform module at "."
15:10:18.567 INFO Reading required version from constraint: ">= 1.9.8, < 1.10"
15:10:18.568 INFO Matched version: "1.9.8"
15:10:18.569 INFO Switched Terraform to version "1.9.8"
Initializing the backend...
Initializing provider plugins...
- Finding cloudflare/cloudflare versions matching "~> 5.1"...
- Using previously-installed cloudflare/cloudflare v5.1.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Tue Mar 11 15:10:19 PDT 2025
Running plan:
terraform plan > /dev/null  1.71s user 0.67s system 1% cpu 3:11.89 total
Tue Mar 11 15:13:30 PDT 2025
Changing to v4:
15:13:30.987 INFO Reading version from Terraform module at "."
15:13:31.152 INFO Reading required version from constraint: ">= 1.9.8, < 1.10"
15:13:31.153 INFO Matched version: "1.9.8"
15:13:31.153 INFO Switched Terraform to version "1.9.8"
Initializing the backend...
Initializing provider plugins...
- Finding cloudflare/cloudflare versions matching "~> 4.0"...
- Installing cloudflare/cloudflare v4.52.0...
- Installed cloudflare/cloudflare v4.52.0 (self-signed, key ID C76001609EE3B136)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Tue Mar 11 15:13:33 PDT 2025
Running plan:
terraform plan > /dev/null  0.21s user 0.12s system 32% cpu 0.991 total
Tue Mar 11 15:13:34 PDT 2025
Running curl:
curl -s -X GET -H  -H "Content-Type:application/json"  -o /dev/null  0.02s user 0.02s system 16% cpu 0.262 total
Tue Mar 11 15:13:35 PDT 2025
```

Script source:
```
date
echo "Running curl:"
time curl -s -X GET -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" -H "Content-Type:application/json" https://api.cloudflare.com/client/v4/accounts -o /dev/null
date
echo "Checking cloudflare terraform plugin version:"
grep -A3 'cloudflare =' main.tf
tfswitch ; tf init --upgrade
date
echo "Running plan:"
time tf plan > /dev/null
date
echo "Changing to v4:"
sed -I '' 's/5.1/4.0/' main.tf ; sed -I '' 's/self.result/self.accounts/' main.tf
tfswitch ; tf init --upgrade
date
echo "Running plan:"
time tf plan > /dev/null
date
echo "Running curl:"
time curl -s -X GET -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" -H "Content-Type:application/json" https://api.cloudflare.com/client/v4/accounts -o /dev/null
date
```

The key times:
curl before: 0.265 total
v5 tf provider: 3:11.89 total
v4 tf provider: 0.991 total
curl after: 0.262 total

The only difference is the v5 provider.
I am willing to believe it behaves differently in some fundamental way, that it needs some special configuration or that it's not just "hit the /accounts API endpoint and parse the results" but I can't tell what it is, I can only tell that the performance is very poor.

**Comment by dlacosteGFM** [comment]
Oooooohhhh, I think I found something.  I did two very small changes:

First, output the entire result, not just `result[0].id`
```
output "account_id" {
  value = data.cloudflare_accounts.self.result
}
```

Second, remove the `name = "Example, Inc."` filter
```
data "cloudflare_accounts" "self" {
}
```

It has HUNDREDS of entries in that `[]` : the same thing, over and over and over and over again:
```
      + {
          + created_on = "YYYY-MM-DDT23:40:33Z"
          + id         = "valid ID"
          + name       = "Example, Inc."
          + settings   = {
              + abuse_contact_email              = "webmaster@example.com"
              + default_nameservers              = "cloudflare.standard"
              + enforce_twofactor                = true
              + use_account_custom_ns_by_default = false
            }
        },
```

just over and over and over and over again.  It filled up my screen buffer [9000 lines]

I am really thinking the problem is one with paging: it has one page of results and doesn't know there is only one page total so it's trying again (and again and....)

**Comment by dlacosteGFM** [comment]
....EXACTLY 1000 times.

Is there a limit in the cloudflare-go library of 1000 pages maximum?

**Comment by driesgroblerw** [comment]
Just a note I observed today, maybe someone else can corroborate this. 

Using a User API Token, I get an immediate result: 
```
data.cloudflare_accounts.primary: Refresh complete after **1s** [name=redacted]
```

Versus using an Account API Token: 
```
data.cloudflare_accounts.primary: Refresh complete after **4m52s** [name=redacted]
```

To reproduce this, I have 2 tokens with the same permissions, one a User API Token and the other a Account API Token. 
1. Update the terraform to the User API Token
- Run a terraform plan
- See the result in sub-1s
2. Update the terraform to the Account API Tokens
- Run a terraform plan
- **See the result in 3+ minutes**

**Comment by jhutchings1** [comment]
Fascinating. We'll have engineering have a look and see if we can't sort out why you're seeing that.

**Comment by jhutchings1** [comment]
I reactivated this issue since Actions found it was stale. This one is still important, and we've sent to the appropriate team.

**Comment by mattduguid** [comment]
this looks closer to our issue originally logged here https://github.com/cloudflare/terraform-provider-cloudflare/issues/5505#issuecomment-3169560124

we had only upgraded from v4 to v5 of the provider and hit rate limits, we did make the change from a user token to an account token though which @driesgroblerw mentioned

in short term we worked around our issue by baking the account_id in as var using data.cloudflare_account instead of data.cloudflare_accounts,

data "cloudflare_account" "company" {
  account_id = "<ID>" 
}

**Comment by jlec** [comment]
I can confirm, seems to be an account token vs user token issue in v5.

**Comment by driesgroblerw** [comment]
@jhutchings1 Has there been any movement on this issue?

**Comment by jhutchings1** [comment]
> [@jhutchings1](https://github.com/jhutchings1) Has there been any movement on this issue?

I'll ping engineering on this. Thanks!

**Comment by KaydeeDee** [comment]
Hi there - this issue has been resolved! Let me know if you see it come back up.

**Comment by driesgroblerw** [comment]
@KaydeeDee , 
I tested with the Terraform Provider 5.13.0 (Released 2025-11-21) and I am still seeing the same result. 

I used @mattduguid 's suggestion of `cloudflare_account` with `account_id` and this allowed the terraform plan to run almost immediately. 

With which version of the provider are you planning to release this fix?

**Comment by jeremywall** [comment]
Using Provider 5.15.0 and `cloudflare_accounts` is still broken as described above when using an account API token. The output of `cloudflare_accounts` is a list of the 1 account 1000 times. I just switched to a user token and it returns nearly instantly with the result containing just the 1 account I have access to listed only one time.

**Comment by CapMousse** [comment]
Same issue here, using `cloudflare_accounts` with the provider 5.18 result in 8 minutes of waiting for terraform to read the data:

```
data "cloudflare_accounts" "self" {}
```

**Comment by AleksandrKls** [comment]
The problem still actual

Terraform version: 5.18

```
data "cloudflare_accounts" "account_data" {
  name = "MyAccount"
}

///

terraform plan
data.cloudflare_accounts.account_data: Reading...
module.sso.cloudflare_sso_connector.connector: Refreshing state...
module.sso.cloudflare_dns_record.dns_record: Refreshing state...
data.cloudflare_accounts.account_data: Still reading... [00m10s elapsed]
...
data.cloudflare_accounts.account_data: Still reading... [08m01s elapsed]
data.cloudflare_accounts.account_data: Read complete after 8m4s

Changes to Outputs:
  + data = {
...
```

**Comment by AleksandrKls** [comment]
@jhutchings1 @KaydeeDee hello

Sorry for disturbing, but could you please let me know if you accept external pull requests? I’ve identified another bug that I probably should be able to fix myself and submit for your review, if that would be useful

**Comment by musa-cf** [comment]
Re-opening this issue, since it is still present in the latest release. We'll take a look, and if we need to forward it to the service team, we will.

**Comment by thoro** [comment]
@musa-cf I have root caused it:


### What happens

A `cloudflare_accounts` data source without `max_items` takes ~6 minutes to read.
It issues 1000 sequential `GET /accounts` requests for an account list of size 1.

### Reproduction

```hcl
data "cloudflare_accounts" "this" {
  name = "<your account name>"
}
```

Plan sits on Still reading... for minutes. A goroutine dump shows the provider in
account.(*AccountsDataSource).Read → pagination.(*V4PagePaginationArray).GetNextPage.

### Cause

GET /accounts clamps out-of-range pages instead of returning an empty result — page 2
returns page 1's content, while correctly reporting total_pages: 1:

page=1 -> {"n":1,"info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1}}
page=2 -> {"n":1,"info":{"page":2,"per_page":20,"total_pages":1,"count":1,"total_count"

V4PagePaginationArrayResultInfo (cloudflare-go v7.8.0, packages/pagination/pagination.g
models only page and per_page, so total_pages / total_count are discarded.
GetNextPage's only termination condition is len(r.Result) == 0, which therefore never
occurs, and internal/services/account/list_data_source.go:76-92 loops until
len(acc) >= maxItems (default 1000).

Note /zones paginates correctly and returns an empty page past the end, so this only
bites endpoints that clamp — but the pager has no defence either way.

### Possible Fix

Model total_pages/total_count in V4PagePaginationArrayResultInfo (and its
apijson.Field metadata struct), then terminate on it:

if r.ResultInfo.TotalPages > 0 && r.ResultInfo.Page >= r.ResultInfo.TotalPages {
    return nil, nil
}

This short-circuits on page 1 and never issues the second request.

### Workaround

max_items = 1, which breaks before GetNextPage is called.

### Versions

terraform-provider-cloudflare v5.23.0 · cloudflare-go v7.8.0 · OpenTofu, darwin_arm64
