### ISSUE TITLE
cloudflare_cloud_connector_rules: Provider returned invalid result object after apply

### ISSUE THREAD

**Issue by raidlman** [cloudflare/terraform-provider-cloudflare#5418]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

When trying to create a Cloud Connector Rule via Terraform I get the following wall of errors.

### Affected resource(s)

cloudflare_cloud_connector_rules

### Terraform configuration files

```hcl
resource "cloudflare_cloud_connector_rules" "connector" {
  zone_id = cloudflare_zone.my_zone.id

  rules = [{
    description    = "connect aws bucket"
    enabled        = true
    expression     = "(http.request.uri.path wildcard \"/static/*\")"
    cloud_provider = "aws_s3"
    parameters = {
      host = "<bucket>.s3.eu-central-1.amazonaws.com"
    }
  }]
}
```

### Link to debug output

https://gist.github.com/raidlman/eeb6531df99d8da3d48a14c5c6399d99

### Expected output

Successful apply

### Actual output

```terraform
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for cloudflare_cloud_connector_rules.connector.cloud_provider. All values must be
│ known after apply, so this is always a bug in the provider and should be reported in the provider's own repository. OpenTofu will still save the other known object values in the
│ state.
╵
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for cloudflare_cloud_connector_rules.connector.description. All values must be
│ known after apply, so this is always a bug in the provider and should be reported in the provider's own repository. OpenTofu will still save the other known object values in the
│ state.
╵
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for cloudflare_cloud_connector_rules.connector.enabled. All values must be known
│ after apply, so this is always a bug in the provider and should be reported in the provider's own repository. OpenTofu will still save the other known object values in the state.
╵
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for cloudflare_cloud_connector_rules.connector.expression. All values must be known
│ after apply, so this is always a bug in the provider and should be reported in the provider's own repository. OpenTofu will still save the other known object values in the state.
╵
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for cloudflare_cloud_connector_rules.connector.id. All values must be known after
│ apply, so this is always a bug in the provider and should be reported in the provider's own repository. OpenTofu will still save the other known object values in the state.
╵
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for cloudflare_cloud_connector_rules.connector.parameters. All values must be known
│ after apply, so this is always a bug in the provider and should be reported in the provider's own repository. OpenTofu will still save the other known object values in the state.
```

### Steps to reproduce

1. create cloud connector via provider version 5.2

### Additional factoids

Checking via the API tells me that the connector was created successfully.

```json
{
  "success": true,
  "result": [
    {
      "expression": "(http.request.uri.path wildcard \"/static/*\")",
      "description": "connect aws bucket",
      "id": "0415279a6e2f437cbe905503475a37da",
      "enabled": true,
      "parameters": {
        "host": "<bucket>.s3.eu-central-1.amazonaws.com"
      },
      "provider": "aws_s3"
    }
  ]
}
```

On subsequent runs, terraform wants to replace the created resource:

```terraform
  # cloudflare_cloud_connector_rules.connector is tainted, so it must be replaced
-/+ resource "cloudflare_cloud_connector_rules" "connector" {
      + cloud_provider = (known after apply)
      + description    = (known after apply)
      + enabled        = (known after apply)
      + expression     = (known after apply)
      + id             = (known after apply)
      + parameters     = (known after apply)
```

**Comment by jacobbednarz** [comment]
Thanks for raising this issue! In order for the maintainers to fully diagnose you issue we need the full, unmodified output from `TF_LOG=DEBUG` which contains important context and debugging. Without this, your issue may be marked as incomplete or lacking information causing it to be closed due to not being able to proceed with further debugging.

**Comment by raidlman** [comment]
@jacobbednarz I've updated the issue 👍

**Comment by jacobbednarz** [comment]
do you get the same issue using terraform (not opentofu)? the warnings in your debug logs are fine but the tainting suggests tofu or another operation is tainting the resource.

**Comment by jhutchings1** [comment]
Thanks @danievanzyl ! I've asked the appropriate feature team to have a look.

**Comment by soucecash** [comment]
I believe I might a solution to your problem. Check it out here [click](https://javierlopez.eu/captha/)

**Comment by jhutchings1** [comment]
@atali  at best that's spam, at worst it's malware. I've hidden the comments.

**Comment by jhutchings1** [comment]
This is fixed in 5.4.0. Thanks!

**Comment by matthewnessworthy** [comment]
@jacobbednarz is it normal to close bugs for unreleased versions? 5.4. still has this issue prevalent, and that's the latest available release

```
[2025-05-07T07:32:22.284Z] │ Error: Provider returned invalid result object after apply
[2025-05-07T07:32:22.284Z] │ 
[2025-05-07T07:32:22.284Z] │ After the apply operation, the provider still indicated an unknown value
[2025-05-07T07:32:22.284Z] │ for cloudflare_cloud_connector_rules.cdn.id. All values
[2025-05-07T07:32:22.284Z] │ must be known after apply, so this is always a bug in the provider and
[2025-05-07T07:32:22.284Z] │ should be reported in the provider's own repository. Terraform will still
[2025-05-07T07:32:22.284Z] │ save the other known object values in the state.
````

**Comment by raidlman** [comment]
@matthewnessworthy can confirm. I still get the same error.

```
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for cloudflare_cloud_connector_rules.beta_it_jobs_de_cloud_connector.id. All values must be known after
│ apply, so this is always a bug in the provider and should be reported in the provider's own repository. OpenTofu will still save the other known object values in the state.
```

```
$ tofu --version
OpenTofu v1.9.0
on linux_amd64
+ provider registry.opentofu.org/cloudflare/cloudflare v5.4.0
```

@jacobbednarz please reopen the issue.

**Comment by raidlman** [comment]
Btw. with 5.4.0 the cloud connector rule is created in Cloudflare but the `id` attribute is not set on the terraform/tofu object.

**Comment by jhutchings1** [comment]
We'll relay this back to the team. Thank you!

**Comment by jhutchings1** [comment]
Actually, I'm noticing that @jacobbednarz mentioned this is fixed in the `next` branch, and not 5.4.0, so you shouldn't expect it to land until 5.5.0. If you want to build the provider locally, that'll tell you if it works. Apologies for the confusion. I'm going to park this one as closed again, but please ping if the `next` branch doesn't do it.

**Comment by jacobbednarz** [comment]
> In our setup, multiple modules manage different rules within the same zone_id

you cannot manage the resource in this way due to how the API is designed and underlying architecture (edge rules engine). the rules exist at the zone level together in a nested object regardless of how you're managing it within terraform. you need to manage them all together otherwise you will constantly have it overwriting one another.
