### ISSUE TITLE
cloudflare_zone showing changes in plan after following upgrade steps from v4.52.0 to v5.2.0 (for both grit and import techniques)

### ISSUE THREAD

**Issue by mig5** [cloudflare/terraform-provider-cloudflare#5472]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

The issue seems a little bit like https://github.com/cloudflare/terraform-provider-cloudflare/issues/5169 but that is supposedly fixed in v5.2.0. I didn't try an `apply` to see if it throws an error.

Might it also be similar to the 'known after apply attributes' problem described in other resources in https://github.com/cloudflare/terraform-provider-cloudflare/issues/5419 ?

### Terraform and Cloudflare provider version

OpenTofu v1.7.1
on linux_amd64
+ provider registry.opentofu.org/cloudflare/cloudflare v5.2.0
+ provider registry.opentofu.org/hashicorp/google v3.90.0
+ provider registry.opentofu.org/hashicorp/google-beta v3.90.0
+ provider registry.opentofu.org/hashicorp/http v2.1.0
+ provider registry.opentofu.org/hashicorp/random v3.1.0

### Affected resource(s)

cloudflare_zone

### Terraform configuration files

```hcl
resource "cloudflare_zone" "example" {
  name = "example.com"
  account = {
    id = var.cloudflare_account_id
  }
}
```

### Link to debug output

-

### Expected output

The migration guide at https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/migrating-renamed-resources says that running the `plan` after pushing the state, should show no difference.

### Actual output
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu will perform the following actions:

  # cloudflare_zone.example will be updated in-place
  ~ resource "cloudflare_zone" "example" {
      ~ activated_on          = "2020-05-21T15:23:25Z" -> (known after apply)
      ~ created_on            = "2020-05-21T15:22:17Z" -> (known after apply)
      ~ development_mode      = 0 -> (known after apply)
        id                    = "xxxxxxxxxxxxxxxx"
      ~ meta                  = {
          + cdn_only                 = (known after apply)
          ~ custom_certificate_quota = 1 -> (known after apply)
          + dns_only                 = (known after apply)
          + foundation_dns           = (known after apply)
          ~ page_rule_quota          = 50 -> (known after apply)
          ~ phishing_detected        = false -> (known after apply)
          ~ step                     = 2 -> (known after apply)
        } -> (known after apply)
      ~ modified_on           = "2020-05-29T19:09:16Z" -> (known after apply)
        name                  = "example.com"
      ~ name_servers          = [
          - "abby.ns.cloudflare.com",
          - "jake.ns.cloudflare.com",
        ] -> (known after apply)
      + original_dnshost      = (known after apply)
      ~ original_name_servers = [
          - "abby.ns.cloudflare.com",
          - "jake.ns.cloudflare.com",
        ] -> (known after apply)
      ~ original_registrar    = "gandi sas (id: 81)" -> (known after apply)
      ~ owner                 = {
          ~ id   = "xxxxxxxxxxxxxxxxxxxx" -> (known after apply)
          ~ name = "Example" -> (known after apply)
          ~ type = "organization" -> (known after apply)
        } -> (known after apply)
      ~ status                = "active" -> (known after apply)
      - vanity_name_servers   = [] -> null
      + verification_key      = (known after apply)
        # (3 unchanged attributes hidden)
    }
```
### Steps to reproduce

Note I am using the 'tf' abstraction tool with OpenTofu but I don't think it should matter. This is what I did to try and upgrade:

1. Set up a cloudflare_zone with v4.52.0
2. Update the attributes with `grit apply github.com/cloudflare/terraform-provider-cloudflare#cloudflare_terraform_v5`
3. `tf state pull > terraform.tfstate`
4. `grit apply github.com/cloudflare/terraform-provider-cloudflare#cloudflare_terraform_v5_attribute_renames_state terraform.tfstate`
5. `grit apply github.com/cloudflare/terraform-provider-cloudflare#cloudflare_terraform_v5_resource_renames_configuration` (no changes as the cloudflare_zone resource itself doesn't change name)
6. `grit apply github.com/cloudflare/terraform-provider-cloudflare#cloudflare_terraform_v5_resource_renames_state terraform.tfstate`
7. `tf state push terraform.tfstate`
8. `tf plan`

### Additional factoids

Even when I don't use the grit technique, and instead do a `tf state rm cloudflare_zone.example; tf import cloudflare_zone.example xxxxxxxxxxx`, I still see the plan 'diff' above. Why is this? I understood that with the latest v5 provider, after either the grit technique or a manual import, I should expect to see no 'diff' in the plan.

**Comment by jacobbednarz** [comment]
Thanks for raising this issue! In order for the maintainers to fully diagnose you issue we need the full, unmodified output from `TF_LOG=DEBUG` which contains important context and debugging. Without this, your issue may be marked as incomplete or lacking information causing it to be closed due to not being able to proceed with further debugging.

**Comment by TheEdgeOfRage** [comment]
@mig5 for us the solution was to add the vanity nameservers to the zone:

```hcl
resource "cloudflare_zone" "example_com" {
  account = {
    id = local.cloudflare_account_id
  }
  name                = "example.com"
  vanity_name_servers = []
}
```

This resolves the spurious diff 🤷

**Comment by TheEdgeOfRage** [comment]
Yeah, the v5 of this provider seems to be exhibiting issues like this across various resources :/ We've had a similar problem on dns_records as well, having just the subdomain like `name = "www"` was causing a diff saying it would change the name from `www.example.com` to just `www`. If we change the name to be `www.example.com` it stops trying to change it, even tho both should be valid domains

**Comment by jhutchings1** [comment]
@musa-cf can you take next step on this one? Looks like a schema issue we need to take back to the team.

**Comment by musa-cf** [comment]
The work to address this has been completed internally, so the fix will be included in `v.5.6.0`. Sorry for the inconvenience!

**Comment by danielnperry** [comment]
I can also confirm that setting `vanity_name_servers = []` stopped the zone diff issue.  I previously had it set to  `vanity_name_servers = null`

**Comment by musa-cf** [comment]
This should be fixed in the latest `v5.6.0`. Thank you for your patience and feel free to re-open this if you experience this issue again!

**Comment by javgo** [comment]
Hi. The issue is still happening for us. I even tried deleting the records and re-creating them again via terraform. Once the records are in the state, the plan is constantly trying to update them

```
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "5.6.0"
    }
  }
}
```

run `terraform plan`

Output: `Plan: 0 to add, 61 to change, 0 to destroy.`

remove a given record and plan again

Output `Plan: 1 to add, 60 to change, 0 to destroy`

apply the plan. the record gets re-created

run `terraform plan` again

Output: `Plan: 0 to add, 61 to change, 0 to destroy.`

**Comment by jhutchings1** [comment]
@javgo can you open a new bug for your issue? I want to make sure we've got the appropriate repro steps for what you're seeing. If you can try the latest version, that'd be best. Thanks!

**Comment by javgo** [comment]
> [@javgo](https://github.com/javgo) can you open a new bug for your issue? I want to make sure we've got the appropriate repro steps for what you're seeing. If you can try the latest version, that'd be best. Thanks!

Hi @jhutchings1 Thanks for your message. I'm having the same issue describe here https://github.com/cloudflare/terraform-provider-cloudflare/issues/5858 so no need to re-open this specific ticket from my side
