### ISSUE TITLE
cloudflare_zero_trust_device_custom_profile errors our when not specifying exclude

### ISSUE THREAD

**Issue by PI-Victor** [cloudflare/terraform-provider-cloudflare#5514]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.11.3
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v5.3.0
+ provider registry.terraform.io/hashicorp/random v3.6.3

```hcl
terraform {
  required_version = ">=1.10.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6.2"
    }
  }
}
```

### Affected resource(s)

cloudflare_zero_trust_device_custom_profile

### Terraform configuration files

```hcl
resource "cloudflare_zero_trust_device_custom_profile" "example_zero_trust_device_custom_profile" {
  account_id = local.account_id
  match      = "identity.email == \"test@cloudflare.com\""
  name       = "Allow Developers"
  precedence = 100
}
```

### Link to debug output

https://gist.github.com/PI-Victor/fb9a1efdb7b6b71769e38e8af7669661

### Expected output

When the resource is created without specifying exclude, it will error out on subsequent `terraform apply` operations.

### Actual output

e.g.:

```hcl
resource "cloudflare_zero_trust_device_custom_profile" "example_zero_trust_device_custom_profile" {
  account_id = local.account_id
  match      = "identity.email == \"test@cloudflare.com\""
  name       = "Allow Developers"
  precedence = 100
}
```

```shell
➜  cloudflare-tf terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_zero_trust_device_custom_profile.example_zero_trust_device_custom_profile will be created
  + resource "cloudflare_zero_trust_device_custom_profile" "example_zero_trust_device_custom_profile" {
      + account_id        = "redacted"
      + default           = (known after apply)
      + exclude           = (known after apply)
      + fallback_domains  = (known after apply)
      + gateway_unique_id = (known after apply)
      + id                = (known after apply)
      + include           = (known after apply)
      + match             = "identity.email == \"test@cloudflare.com\""
      + name              = "Allow Developers"
      + policy_id         = (known after apply)
      + precedence        = 100
      + service_mode_v2   = (known after apply)
      + target_tests      = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_zero_trust_device_custom_profile.example_zero_trust_device_custom_profile: Creating...
cloudflare_zero_trust_device_custom_profile.example_zero_trust_device_custom_profile: Creation complete after 1s [id=7d8c169b-08e7-4f3b-afc3-da834da93177]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

```shell
➜  cloudflare-tf terraform apply
cloudflare_zero_trust_device_custom_profile.example_zero_trust_device_custom_profile: Refreshing state... [id=7d8c169b-08e7-4f3b-afc3-da834da93177]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_zero_trust_device_custom_profile.example_zero_trust_device_custom_profile will be updated in-place
  ~ resource "cloudflare_zero_trust_device_custom_profile" "example_zero_trust_device_custom_profile" {
      - allow_mode_switch              = false -> null
      - allow_updates                  = false -> null
      - allowed_to_leave               = true -> null
      - auto_connect                   = 0 -> null
      - captive_portal                 = 180 -> null
      ~ default                        = false -> (known after apply)
      - description                    = "" -> null
      - disable_auto_fallback          = false -> null
      - enabled                        = true -> null
      ~ exclude                        = [
          - {
              - address = "10.0.0.0/8" -> null
            },
          - {
              - address = "100.64.0.0/10" -> null
            },
          - {
              - address     = "169.254.0.0/16" -> null
              - description = "DHCP Unspecified" -> null
            },
          - {
              - address = "172.16.0.0/12" -> null
            },
          - {
              - address = "192.0.0.0/24" -> null
            },
          - {
              - address = "192.168.0.0/16" -> null
            },
          - {
              - address = "224.0.0.0/24" -> null
            },
          - {
              - address = "240.0.0.0/4" -> null
            },
          - {
              - address     = "255.255.255.255/32" -> null
              - description = "DHCP Broadcast" -> null
            },
          - {
              - address     = "fe80::/10" -> null
              - description = "IPv6 Link Local" -> null
            },
          - {
              - address = "fd00::/8" -> null
            },
          - {
              - address = "ff01::/16" -> null
            },
          - {
              - address = "ff02::/16" -> null
            },
          - {
              - address = "ff03::/16" -> null
            },
          - {
              - address = "ff04::/16" -> null
            },
          - {
              - address = "ff05::/16" -> null
            },
        ] -> (known after apply)
      - exclude_office_ips             = false -> null
      ~ fallback_domains               = [
          - {
              - suffix = "home.arpa" -> null
            },
          - {
              - suffix = "intranet" -> null
            },
          - {
              - suffix = "internal" -> null
            },
          - {
              - suffix = "private" -> null
            },
          - {
              - suffix = "localdomain" -> null
            },
          - {
              - suffix = "domain" -> null
            },
          - {
              - suffix = "lan" -> null
            },
          - {
              - suffix = "home" -> null
            },
          - {
              - suffix = "host" -> null
            },
          - {
              - suffix = "corp" -> null
            },
          - {
              - suffix = "local" -> null
            },
          - {
              - suffix = "localhost" -> null
            },
          - {
              - suffix = "invalid" -> null
            },
          - {
              - suffix = "test" -> null
            },
        ] -> (known after apply)
      ~ gateway_unique_id              = "redacted" -> (known after apply)
        id                             = "7d8c169b-08e7-4f3b-afc3-da834da93177"
      + include                        = (known after apply)
        name                           = "Allow Developers"
      - register_interface_ip_with_dns = true -> null
      ~ service_mode_v2                = {
          ~ mode = "warp" -> (known after apply)
          + port = (known after apply)
        } -> (known after apply)
      - support_url                    = "" -> null
      - switch_locked                  = false -> null
      + target_tests                   = (known after apply)
      - tunnel_protocol                = "" -> null
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_zero_trust_device_custom_profile.example_zero_trust_device_custom_profile: Modifying... [id=7d8c169b-08e7-4f3b-afc3-da834da93177]
╷
│ Error: failed to make http request
│
│   with cloudflare_zero_trust_device_custom_profile.example_zero_trust_device_custom_profile,
│   on warp_profiles.tf line 36, in resource "cloudflare_zero_trust_device_custom_profile" "example_zero_trust_device_custom_profile":
│   36: resource "cloudflare_zero_trust_device_custom_profile" "example_zero_trust_device_custom_profile" {
│
│ PATCH "https://api.cloudflare.com/client/v4/accounts/ad3e1d4f151beb636e71f2e720c55940/devices/policy/7d8c169b-08e7-4f3b-afc3-da834da93177": 400 Bad Request
│ {"result":null,"success":false,"errors":[{"code":2004,"message":"bad device request"}],"messages":[]}
│
```

It looks like on subsequent apply operations (without any modification to the resource) it will try to delete exclude and fallback_domains.

### Steps to reproduce

* Create a new resource with the above mentioned example
* terraform apply <- this will run and the resource will be created
* terraform apply <- this will mark the exclude and fallback_domains fields (and a few other fields) as null and will try to destroy the resource. This will fail with the above output.

### Additional factoids

This is not the only resource that has this issue.
This will happen with fallback_domains as well.
**Exclude is an optional field that has some mandatory default entries created, same as fallback_domains.**

if you create the resource with an empty exclude, e.g.:

```hcl
resource "cloudflare_zero_trust_device_custom_profile" "example_zero_trust_device_custom_profile" {
  account_id = local.account_id
  match      = "identity.email == \"test@cloudflare.com\""
  name       = "Allow Developers"
  precedence = 100
  exclude = []
}
```
This does not cause issues

**Comment by jhutchings1** [comment]
We'll take a look internally. Thanks!

**Comment by jhutchings1** [comment]
This one should be fixed in the next Terraform release.

**Comment by paweloczadly** [comment]
Hi @jhutchings1 ,

Following up on this issue. I've tested this with 5.8.4 (using Terraform 1.13) and can confirm the issue still persists.

I've created a PR with a potential fix for this:

https://github.com/cloudflare/terraform-provider-cloudflare/pull/5990

Please let me know if you need any additional information from my side. Thanks!

**Comment by jhutchings1** [comment]
I reactivated and asked engineering to have a look. I'm not sure about the PR, a lot of this code is autogenerated, so that may not work.

**Comment by paweloczadly** [comment]
Hi @jhutchings1 ,

Thanks for reopening the issue and your answer. This functionality is really crucial for us. We have multiple Zero Trust WARP profiles where we manage split tunnels. We would love to have this functionality in the provider v5.

**Comment by paweloczadly** [comment]
Hi @jhutchings1, I'm following up on this issue and the [PR](https://github.com/cloudflare/terraform-provider-cloudflare/pull/5990). Do you have any updates or is there anything I can do to help move this forward?

**Comment by jhutchings1** [comment]
@paweloczadly Thanks for the check in. I pinged the team for a status update on this. Engineering has been looking at it. Updates soon!

**Comment by KaydeeDee** [comment]
Hi there - this is resolved. Please let us know if you see it creep back up.

**Comment by paweloczadly** [comment]
@KaydeeDee, @jhutchings1, thank you for the update. It still **does not** work and returns the same output:

```
│ Error: failed to make http request
│ 
│   with cloudflare_zero_trust_device_custom_profile.warp_profile,
│   on main.tf line 5, in resource "cloudflare_zero_trust_device_custom_profile" "warp_profile":
│    5: resource "cloudflare_zero_trust_device_custom_profile" "warp_profile" {
│ 
│ PATCH
│ "https://api.cloudflare.com/client/v4/accounts/00000000000000000000000000000000/devices/policy/00000000-0000-0000-0000-000000000000":
│ 400 Bad Request
│ {"result":null,"success":false,"errors":[{"code":2004,"message":"bad device
│ request"}],"messages":[]}
│ 
╵
```

### Environment

```
Terraform v1.4.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v5.10.1
```

**Comment by kereza** [comment]
Hello and thanks.

But I also confirm that it still fails. I started to follow this thread recently :)

**Comment by KaydeeDee** [comment]
Hi All - i've reopened and let the team working on it know.

**Comment by paweloczadly** [comment]
Hi @KaydeeDee 

Following up on this thread. It's been a couple of weeks since your message.

Do you have any update on the status of the fix? Is there anything I can do from my side to help move this forward?

Thanks!

**Comment by rupalims** [comment]
This is part of of provider release 5.13.
Could you verify and confirm?

**Comment by paweloczadly** [comment]
Thank you @rupalims for the update. I have tested it and can confirm it's working on my side.
