### ISSUE TITLE
cloudflare_dns_record: A lot of resources will be updated in-place (without changes in terraform configuration files)

### ISSUE THREAD

**Issue by DavydDerkach** [cloudflare/terraform-provider-cloudflare#5517]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
terraform -v
Terraform v1.9.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v5.3.0
+ provider registry.terraform.io/hashicorp/aws v5.94.1
```

### Affected resource(s)

cloudflare_dns_record
cloudflare_ruleset
cloudflare_page_rule

### Terraform configuration files

```hcl
#DNS_Record

resource "cloudflare_dns_record" "a_records" {
  for_each = var.a_records

  zone_id = var.cf_zone_id
  name    = each.value.name
  type    = "A"
  content = each.value.content
  proxied = each.value.proxied
  ttl     = each.value.ttl
  comment = each.value.comment
}

resource "cloudflare_dns_record" "cname_records" {
  for_each = var.cname_records

  zone_id = var.cf_zone_id
  name    = each.value.name
  type    = "CNAME"
  content = each.value.content
  proxied = each.value.proxied
  ttl     = each.value.ttl
  comment = each.value.comment
}

#WAF_Rules

resource "cloudflare_ruleset" "terraform_managed_resource_4fd0e9f875a441c59512e0ce6bd3e012" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_firewall_custom"
  zone_id = var.cf_zone_id
  rules = [
    {
      action = "skip"
      action_parameters = {
        phases  = []
        ruleset = "current"
      }
      description = "Allow www."
      enabled     = true
      expression  = "(http.request.full_uri contains \"www.test10.example\")"
      logging = {
        enabled = true
      }
    },
    {
      action = "skip"
      action_parameters = {
        phases  = ["http_request_sbfm", "http_request_firewall_managed", "http_ratelimit"]
        products = ["zoneLockdown", "uaBlock", "bic", "hot", "securityLevel", "rateLimit", "waf"]
        ruleset = "current"
      }
      description = "Whitelist technical IPs"
      enabled     = true
      expression  = "*****"
      logging = {
        enabled = true
      }
    },
    {
      action = "skip"
      action_parameters = {
        phases = []
        ruleset = "current"
      }
      description = "Whitelist IPs"
      enabled     = true
      expression  = "****"
      logging = {
        enabled = true
      }
    },
    {
      action = "block"
      description = "Block all denied geo"
      enabled     = true
      expression  = "****"
    },
    {
      action = "block"
      description = "Block all denied geo, part 2"
      enabled     = true
      expression  = "***"
    }
  ]
}

#Page_Rules

resource "cloudflare_page_rule" "disable_security_wildcard" {
  zone_id = var.cf_zone_id
  target  = "www.test10.example/*"

  actions = {
    disable_security     = true
    waf                  = "off"
  }

  priority = 2
  status   = "active"
}

resource "cloudflare_page_rule" "disable_security" {
  zone_id = var.cf_zone_id
  target  = "www.test10.example/"

  actions = {
    disable_security     = true
    waf                  = "off"
  }

  priority = 1
  status   = "active"
}
```

### Link to debug output

https://gist.github.com/DavydDerkach/38f83047f3f79134c80defaeb917d13b

### Panic output

--

### Expected output

I expect to see that there wont be any changes in terraform plan/apply since I have not changed configuration.

### Actual output

May be found here: https://gist.github.com/DavydDerkach/38f83047f3f79134c80defaeb917d13b

### Steps to reproduce

1. Create tf config files with resources same to mine.
2. Run terraform plan/apply
3. Verify that there are resources marked "will be updated in place", but tf configurations wasn`t changed.

### Additional factoids

When I create redirect rules with your provider, everything works fine as well as txt dns records. They do not show any changes.

As example part of redirect rule:
```
resource "cloudflare_ruleset" "redirect_de" {
   zone_id = var.cf_zone_id
   name    = "default"
   kind    = "zone"
   phase   = "http_request_dynamic_redirect"
```

### References

---

**Comment by lukasPresencia** [comment]
Same issue at least with cloudflare_ruleset
`  
# module.cloudflare_account_waf.cloudflare_ruleset.rate_limit will be updated in-place
  ~ resource "cloudflare_ruleset" "rate_limit_authentication" {
        id          = "xxxx"
        name        = "Rate limiting"
      ~ rules       = [
          ~ {
              ~ id          = "yyyy" -> (known after apply)
              ~ ref         = "yyyy" -> (known after apply)
                # (5 unchanged attributes hidden)
            },
        ]
`
No changes after apply, still wants to update the same fields at apply #2

**Comment by ChocoChipset** [comment]
Thanks @jhutchings1! Fingers crossed for a fix soon.

**Comment by perlboy** [comment]
_Endless_ drift... this is a pretty basic expected behaviour of a terraform provider, when will it be fixed?

Here's another example

```
  ~ resource "cloudflare_dns_record" "sample" {
      + comment             = (known after apply)
      + comment_modified_on = (known after apply)
      ~ created_on          = "2025-05-04T07:21:18Z" -> (known after apply)
      + data                = (known after apply)
        id                  = "abcdef1234"
      ~ meta                = jsonencode({}) -> (known after apply)
      ~ modified_on         = "2025-05-04T23:43:17Z" -> (known after apply)
        name                = "_abcd1234.customer.com"
      ~ proxiable           = false -> (known after apply)
      ~ settings            = {
          + flatten_cname = false
          + ipv4_only     = (known after apply)
          + ipv6_only     = (known after apply)
        }
        tags                = []
      + tags_modified_on    = (known after apply)
        # (5 unchanged attributes hidden)
    }
```

All of the "known after apply" are injected by the provider. Turns plans involving 50+ domains into complete custard.

**Comment by RafPe** [comment]
> _Endless_ drift... this is a pretty basic expected behaviour of a terraform provider, when will it be fixed?
> 
> Here's another example
> 
> ```
>   ~ resource "cloudflare_dns_record" "sample" {
>       + comment             = (known after apply)
>       + comment_modified_on = (known after apply)
>       ~ created_on          = "2025-05-04T07:21:18Z" -> (known after apply)
>       + data                = (known after apply)
>         id                  = "abcdef1234"
>       ~ meta                = jsonencode({}) -> (known after apply)
>       ~ modified_on         = "2025-05-04T23:43:17Z" -> (known after apply)
>         name                = "_abcd1234.customer.com"
>       ~ proxiable           = false -> (known after apply)
>       ~ settings            = {
>           + flatten_cname = false
>           + ipv4_only     = (known after apply)
>           + ipv6_only     = (known after apply)
>         }
>         tags                = []
>       + tags_modified_on    = (known after apply)
>         # (5 unchanged attributes hidden)
>     }
> ```
> 
> Off a resource definition that looks like this:
> 
> ```
> resource "cloudflare_dns_record" "sample" {
>   zone_id  =  "abced"
>   content  = "abcdef.com"
>   name     = "_abcd1234.customer.com"
>   proxied  = false
>   settings = {
>     flatten_cname = false
>   }
>   ttl  = 60
>   type = "CNAME"
> }
> ```
> 
> All of the "known after apply" are injected by the provider. Turns plans involving 50+ domains into complete custard.

Experiencing the same - since these are read only values does not feel we are asking for much :)

**Comment by RichardoC** [comment]
At least for cloudflare_dns_record this has happened since 5.1, as I was using that previously without seeing these constant changes required.
tofu state rm && tofu state import doesn't change anything - these changes are still shown

**Comment by cizara** [comment]
hitting the same behaviour in `v5.5.0`

**Comment by nickatct** [comment]
It appears if I specified the full hostname as the value of `cloudflare_dns_record` `name`, the plan will result in `No changes`. For example, if your zone is `example.com`, make `name = "site.example.com"` instead of `name = "site"`.  It's kind of redundant, but it helps us currently.

**Comment by ic4-y** [comment]
While the workaround mentioned worked for me, I still hope this gets fixed! Particularly for migrating already existing records this was fairly annoying.

**Comment by perlboy** [comment]
> It appears if I specified the full hostname as the value of `cloudflare_dns_record` `name`, the plan will result in `No changes`. For example, if your zone is `example.com`, make `name = "site.example.com"` instead of `name = "site"`. It's kind of redundant, but it helps us currently.

This didn't work for us, maybe it's been fixed in a recent version but with a month past and no confirmed fix for a pretty basic issue we've dumped this provider and moved on.

**Comment by RichardoC** [comment]
> > It appears if I specified the full hostname as the value of `cloudflare_dns_record` `name`, the plan will result in `No changes`. For example, if your zone is `example.com`, make `name = "site.example.com"` instead of `name = "site"`. It's kind of redundant, but it helps us currently.
> 
> This didn't work for us, maybe it's been fixed in a recent version but with a month past and no confirmed fix for a pretty basic issue we've dumped this provider and moved on.

Which alternative did you move to?

**Comment by estecker** [comment]
After a V5 update, I had to make these 3 changes to resource "cloudflare_dns_record" to prevent constant plan diff:

```
resource "cloudflare_dns_record" "this" {
  name     = trimsuffix(another_resource, ".")
  content  = trimsuffix(another_resource, ".")
  settings = null
...
```

**Comment by musa-cf** [comment]
The DNS team looked into this, and fixing this will require changes in the API layer, and that work is planned, but not currently being worked on and there's no ETA at this time. The recommendation is to use the workarounds discussed in this thread. We'll leave this issue open until the API changes are made. Thanks for reporting this!

**Comment by philip-harvey** [comment]
> and that work is planned, but not currently being worked on and there's no ETA at this time.

This is ridiculous, the v4 provider worked correctly, and the v5 provider is STILL totally broken and unusable.  The only solution currently is rolling back to v4 provider. Cloudflare needs to do better.

**Comment by perlboy** [comment]
> > This didn't work for us, maybe it's been fixed in a recent version but with a month past and no confirmed fix for a pretty basic issue we've dumped this provider and moved on.
> Which alternative did you move to?

Initially Direct API calls but after a bunch of both business and technical issues we made the decision to drop Cloudflare entirely and migrated to AWS WAF + Route53. We're now in the final stages of canceling our Cloudflare Enterprise account in full.

**Comment by RafPe** [comment]
> > > This didn't work for us, maybe it's been fixed in a recent version but with a month past and no confirmed fix for a pretty basic issue we've dumped this provider and moved on.
> > > Which alternative did you move to?
> 
> Initially Direct API calls but after a bunch of both business and technical issues we made the decision to drop Cloudflare entirely and migrated to AWS WAF + Route53. We're now in the final stages of canceling our Cloudflare Enterprise account in full.

@perlboy I feel the same pain here :( this is no where near a service we would expect. Would you be open to connect outside of Github and maybe share some of your path to move away ? Looking at similar scenarios for my customers

**Comment by philip-harvey** [comment]
Some more info on this drift issue for cloudflare_dns_record
I managed to get the drift to stop, but in order to do so I had to make two changes that both violate the DNS spec, so should be considered high priority bugs for Cloudflare to fix.
The first is that A records for zone example.com must be passed to the API as hostname.example.com
Note that you should not pass the zone to the zone, this should really make hostname.example.com.example.com, but it doesn't
The second thing to note is that a fully qualified DNS name must end in a ".", but the v5 provider breaks if you add a "." on the end to make a correctly formed DNS record.  
In short, I changed every DNS record to be fully qualified, but had to drop the period off the end of the record (fun times!), and for other records such as CNAMEs, I just dropped the period off the end of the record.
Overall the v5 provider is a hot mess, and I'd highly recommend anyone who hadn't upgraded to just stay on the v4 provider.

**Comment by LarsSven** [comment]
We are having similar issues, the workaround does work but it is annoying and redundant.

**Comment by ghost** [comment]
_(This comment is about DNS record names specifically.)_

When a record name of "www" is received by our API, that's (for now) treated as a short form that'll be converted to, say, "www.example.com". This is slightly ambiguous; for example, name "example.com" on zone "example.com" would **not** be treated as a short form; for this reason and for consistency in general it's advisable to always use the unambiguous long form, i.e., including the zone name at the end. The "name" field in our API always represents a full record name, including the zone name. Because the API appends the zone name in its response, Terraform sees it as a diff when the short form is used.

ℹ️ **The correct way to solve this issue** is to always use complete record names in Terraform. This matches our API schema and eliminates any ambiguity. For example, instead of "www", you'd use "www.example.com" as the name.

There is nothing about this that violates the DNS specification, first and foremost because the DNS specification primarily concerns itself with the binary wire format and doesn't say anything about how APIs like ours should behave. Behind the scenes, our Terraform provider uses our public API which has always represented record names in full, including the zone name but without a trailing dot (unless referring to the root zone itself). There have been no changes here — the only difference is that Terraform v5 doesn't support the ambiguous short form.

If the same DNS records need to be present on many different zones, they could probably represented similarly to:

```
resource "cloudflare_record" "www_example_com" {
    zone_id = cloudflare_zone.example_com.id
    name = "www.${cloudflare_zone.example_com.name}"
    // ...
}
```

However, in most cases, it's probably simplest to just include "www.example.com" directly without any string interpolation.

If that doesn't cover anyone's use case for any reason, I'm sure our Product team would love to hear more about it.

Read-only fields being hidden from diffs to make _actual_ diffs easier to spot is out of scope for this comment and I'll defer to @jhutchings1 regarding that.

cc @hannes-cf

**Comment by jhutchings1** [comment]
Thanks @janik-cloudflare , considering your response, I'm resolving this one as a won't fix. 
Customers, really appreciate your patience on this one 🧡

**Comment by perlboy** [comment]
Honestly this is both a usability and customer fail and the fact Cloudflare people can't understand this is a bit mind blowing. I don't have a horse in this race since we've dumped Cloudflare now entirely (Enterprise account >$100K/year spend) but deconstructing the response from @janik-cloudflare:

> This is slightly ambiguous; for example, name "example.com" on zone "example.com" would not be treated as a short form

Correct, the CF API is ambiguous and those writing Terraform rules oppose ambiguity.

> The correct way to solve this issue is to always use complete record names in Terraform. 

According to Cloudflare's opinion _not_ Terraform norms. 

By _requiring_ this what you are doing is _requiring_ a structure to be created that a terraform rule maintainer can then use to obtain both the id and the zone name. The example provided _makes an assumption_ that there is a `cloudflare_zone` resource available, which in many cases there _isn't_ not least of which because it could result in unintended deletions of zones with non-recoverable NS records (i.e we can't force NS record allocation afaik). 

By way of example route53 management in the AWS provider accepts and handles diffs on both, so does Azure's DNS provider and Google's... Cloudflare is the _outlier_ here for no other reason then it thinks it's entitled to be.

> Behind the scenes, our Terraform provider uses our public API which has always represented record names in full, including the zone name but without a trailing dot (unless referring to the root zone itself). There have been no changes here — the only difference is that Terraform v5 doesn't support the ambiguous short form.

Issues Cloudflare has with it's API are of little concern to Terraform users. We use terraform so we don't have to deal with issues individual providers have with their backend APIs. Apparently though if you're a cloudflare customer you are _required_ to consume the Kool-Aid and eat the Cloudflare debt.

The final footnote is that the terraform provider docs for the `name` say `(String) DNS record name (or @ for the zone apex) in Punycode.` so apparently `@` is not considered the short form...

**Comment by RafPe** [comment]
> Thanks [@janik-cloudflare](https://github.com/janik-cloudflare) , considering your response, I'm resolving this one as a won't fix. Customers, really appreciate your patience on this one 🧡

It is hard to believe that you are just ditching this issue and not considering the impact your new provider has on your customers and that it feels like early alpha release more than anything stable.

**Comment by ghost** [comment]
Hi, I'll pass this feedback along to our Product team. It would, however, be immensely helpful to have a more detailed example of a situation where the behavior of provider v5 is inconvenient (i.e., when sharing records across multiple zones). Some (pseudo)code describing such a scenario would be especially appreciated!

---

> By _requiring_ this what you are doing is _requiring_ a structure to be created that a terraform rule maintainer can then use to obtain both the id and the zone name.

Yes, if the same records are reused across many zones. Otherwise, it might be simplest to just add the zone name directly.

> The example provided _makes an assumption_ that there is a `cloudflare_zone` resource available, which in many cases there _isn't_ not least of which because it could result in unintended deletions of zones with non-recoverable NS records (i.e we can't force NS record allocation afaik).

If you're worried about accidental deletion of zone resources, an alternative might be to use "data" instead of "resource" to obtain a read-only zone object that Terraform won't actively manage.

```
data "cloudflare_zone" "example_com" {
    name = "example.com"
    # ...
}
```

Alternatively, the `prevent_destroy` lifecycle attribute on a real zone resource might also help.

If not in a resource or data source, how are the zone IDs currently being stored in your scenario?

> The final footnote is that the terraform provider docs for the `name` say `(String) DNS record name (or @ for the zone apex) in Punycode.` so apparently `@` is not considered the short form...

Good catch. The `@` is considered short form (or some version thereof) and, while it's accepted as an input, would never be returned in responses. We'll update the documentation to clarify that; thanks!

**Comment by jacekn** [comment]
@janik-cloudflare thanks for looking into this!

I don't want to get involved into the conversation about the API correctness but let me point out that the diff issue affect more than just the `name` field.
In our case we cleaned up the `name` field and no longer see diffs for it. However there are still diffs for multiple fields that we keep seeing even if no changes are made to the code. Some examples are `comment`, `meta`, `modified_on`, `tags`, `tags_modified_on` and more. So from our perspective the workaround isn't complete.

**Comment by ghost** [comment]
@jacekn, that makes a lot of sense, and probably makes it quite difficult to even figure out that the "name" field is the cause. I fear this might just be a Terraform limitation but I'll check with our experts who know more about this than I do!

**Comment by RafPe** [comment]
@janik-cloudflare There is also a lowercase implemented ? This is what I get as a diff on my records:

```
  # cloudflare_dns_record.cname_selector2_domainkey_contoso_ai will be updated in-place
  ~ resource "cloudflare_dns_record" "cname_selector2_domainkey_contoso_ai" {
      ~ comment_modified_on = "2025-05-10T14:34:35Z" -> (known after apply)
      ~ content             = "selector2-contoso-ai._domainkey.contosoco.onmicrosoft.com" -> "selector2-contoso-ai._domainkey.ConTosoCo.onmicrosoft.com"
      ~ created_on          = "2025-05-10T14:34:35Z" -> (known after apply)
        id                  = "adcf27d64b72e71684c0e9743e07758e"
      ~ meta                = jsonencode({}) -> (known after apply)
      ~ modified_on         = "2025-06-22T08:33:18Z" -> (known after apply)
        name                = "selector2._domainkey.contoso.ai"
      ~ proxiable           = false -> (known after apply)
      ~ settings            = {
          + flatten_cname = (known after apply)
          + ipv4_only     = (known after apply)
          + ipv6_only     = (known after apply)
        } -> (known after apply)
        tags                = []
      + tags_modified_on    = (known after apply)
        # (5 unchanged attributes hidden)
    }
```

And I cannot just do `tolower()` on all types as values in TXT and SPF records are case sensitive.

**Comment by ghost** [comment]
Hi @RafPe — yes, the DNS API does normalize the contents of CNAME records (and other domain names) in a few ways: lowercasing, replacing Unicode with Punycode, canonicalizing escape sequences, etc.

It's possible that provider v4 ignored differences in letter case. Instead of calling `lower()`, I'd address this by lowercasing the record resource's content directly.

**Comment by RafPe** [comment]
> Hi [@RafPe](https://github.com/RafPe) — yes, the DNS API does normalize the contents of CNAME records (and other domain names) in a few ways: lowercasing, replacing Unicode with Punycode, canonicalizing escape sequences, etc.
> 
> It's possible that provider v4 ignored differences in letter case. Instead of calling `lower()`, I'd address this by lowercasing the record resource's content directly.

Is there a reason why such change between providers ? I now have to selectively modify code/introducing workarounds to make sure CNAMEs using `cloudflare_dns_record` are in lowercase as otherwise I get a number of diffs

**Comment by ghost** [comment]
@RafPe, I don't have any large Terraform deployments myself so please excuse my ignorance, but why not just lowercase them at the source instead of introducing workarounds?

The main reason is that provider v5 is now [auto-generated based on our OpenAPI schemas](https://developers.cloudflare.com/changelog/2025-02-03-terraform-v5-provider/). This allows us to fairly easily make any API resource configurable with Terraform and therefore support a wider set of resources and properties, but has the drawback of making it difficult to introduce custom logic and special cases for individual resources.

The previous provider v4 tried to hide some of the diffs (missing zone names and, apparently, letter case issues), though I don't think it would've handled Punycode or escape sequences.

**Comment by RafPe** [comment]
> [@RafPe](https://github.com/RafPe), I don't have any large Terraform deployments myself so please excuse my ignorance, but why not just lowercase them at the source instead of introducing workarounds?
> 
> The main reason is that provider v5 is now [auto-generated based on our OpenAPI schemas](https://developers.cloudflare.com/changelog/2025-02-03-terraform-v5-provider/). This allows us to fairly easily make any API resource configurable with Terraform and therefore support a wider set of resources and properties, but has the drawback of making it difficult to introduce custom logic and special cases for individual resources.
> 
> The previous provider v4 tried to hide some of the diffs (missing zone names and, apparently, letter case issues), though I don't think it would've handled Punycode or escape sequences.

Just pretty simple - as not all the input data comes statically defined. Some of it comes from external system/other people input and introduces specific layer of requirements that `if CNAME then make lowercase`.  

Since you are generating the provider - would it not be an idea to implement it as part of CI process - that you add function to lower if CNAME ?

**Comment by jacekn** [comment]
> [@jacekn](https://github.com/jacekn), that makes a lot of sense, and probably makes it quite difficult to even figure out that the "name" field is the cause. I fear this might just be a Terraform limitation but I'll check with our experts who know more about this than I do!

@janik-cloudflare apologies but I don't understand. We do use fully qualified names in the `name` field as recommended but we still see constant diffs.
In what sense is the name field the cause here and how can users work around the problem?

**Comment by RafPe** [comment]
> > [@jacekn](https://github.com/jacekn), that makes a lot of sense, and probably makes it quite difficult to even figure out that the "name" field is the cause. I fear this might just be a Terraform limitation but I'll check with our experts who know more about this than I do!
> 
> [@janik-cloudflare](https://github.com/janik-cloudflare) apologies but I don't understand. We do use fully qualified names in the `name` field as recommended but we still see constant diffs. In what sense is the name field the cause here and how can users work around the problem?

Check if you are using CNAMEs and possibly if your diff is the lowercase scenario ( like in my instance )

**Comment by ricohomewood** [comment]
@janik-cloudflare it's not just the `name` field that is the issue here. For example we have this configuration, fairly simple and uses the FQDN for the name in each zone and is lowered:

```terraform
resource "cloudflare_dns_record" "cname_api_gateway" {
  zone_id = local.zone_id
  name    = lower("api-gateway.${local.zone_name}")
  content = local.api_gateway_hostname
  type    = "CNAME"
  proxied = true
  ttl     = 1
  settings = {
    flatten_cname = false
  }
}
```
Yet still there are diffs on all the `CNAME` records like:

```terraform
# module.spektrix_domain.cloudflare_dns_record.cname_api_gateway will be updated in-place
  ~ resource "cloudflare_dns_record" "cname_api_gateway" {
      + comment_modified_on = (known after apply)
      ~ created_on          = "2024-01-09T13:58:03Z" -> (known after apply)
        id                  = "30aeaf5392ebeea35c3600f2d8fbdcaa"
      ~ meta                = jsonencode({}) -> (known after apply)
      ~ modified_on         = "2025-04-28T09:57:40Z" -> (known after apply)
        name                = "api-gateway.spektrix.io"
      ~ proxiable           = true -> (known after apply)
      ~ settings            = {
          + flatten_cname = false
          + ipv4_only     = (known after apply)
          + ipv6_only     = (known after apply)
        }
      ~ tags                = [] -> (known after apply)
      + tags_modified_on    = (known after apply)
        # (5 unchanged attributes hidden)
    }
```
What's interesting here is it thinks `flatten_cname` is a new property when it is not, and exists in state. I also should not be seeing the `comment_modified_on` property here because the docs say `(String) When the record comment was last modified. Omitted if there is no comment.` And you can see I have no `comment` specified in my config so _should_ have been ommited.

These worked fine in the `5.1.0` version of the provider.

Running in TF debug mode, I can see the CloudFlare API response is returning an empty `settings` block even though it was set before and `comment` is set to `null` in the response which could be why we are seeing changes with `comment_modified_on`? are you treating that `null` in the provider properly so that it doesn't think that is a value?

This is what the response from the API looks like:
```json
{"result":{"id":"30aeaf5392ebeea35c3600f2d8fbdcaa","name":"api-gateway.spektrix.io","type":"CNAME","content":"test-apigateway-3c.azurewebsites.net","proxiable":true,"proxied":true,"ttl":1,"settings":{},"meta":{},"comment":null,"tags":[],"created_on":"2024-01-09T13:58:03.365278Z","modified_on":"2025-04-28T09:57:40.639414Z"},"success":true,"errors":[],"messages":[]}
```

UPDATE:
Yes I see you are not handling that `null` properly and setting it as `unknown` in the provider, which is causing an unintended diff:

For the `comment` property:

```
2025-07-17T14:45:52.107+0100 [DEBUG] provider.terraform-provider-cloudflare_v5.7.1.exe: marking computed attribute that is null in the config as unknown: tf_resource_type=cloudflare_dns_record tf_rpc=PlanResourceChange @module=sdk.framework tf_attribute_path="AttributeName(\"comment_modified_on\")" tf_provider_addr=registry.terraform.io/cloudflare/cloudflare tf_req_id=31d873c1-0b88-213f-2ef3-f10e37437c98 @caller=github.com/hashicorp/terraform-plugin-framework@v1.15.0/internal/fwserver/server_planresourcechange.go:538 timestamp="2025-07-17T14:45:52.107+0100"
```
For the `tags` property:

```
2025-07-17T14:45:52.113+0100 [DEBUG] provider.terraform-provider-cloudflare_v5.7.1.exe: marking computed attribute that is null in the config as unknown: tf_rpc=PlanResourceChange @module=sdk.framework tf_req_id=0309c3e4-cff0-1af9-ae7d-0943af5ca41d @caller=github.com/hashicorp/terraform-plugin-framework@v1.15.0/internal/fwserver/server_planresourcechange.go:538 tf_attribute_path="AttributeName(\"tags_modified_on\")" tf_provider_addr=registry.terraform.io/cloudflare/cloudflare tf_resource_type=cloudflare_dns_record timestamp="2025-07-17T14:45:52.113+0100"
```

If these are not set, they should not cause a diff if the API returns them as `null`

UPDATE 2:
I _think_ I found the problem here:

When you configure a `CNAME` that is `proxied` i.e. `proxied = true`, you cannot configure the CNAME flatten property, i.e this will be disabled in the UI as you can't enable it, it will be greyed out. I wonder therefore, when we were setting this in the previous provider, it was abstracting this issue away and not actually setting this property because you can't. Now with version > `5.1.0` the `settings` block is returned empty because that setting could never be configured if `proxied = true`. 
If I remove this part of our configuration so it looks like:

```terraform
resource "cloudflare_dns_record" "cname_api_gateway" {
  zone_id = local.zone_id
  name    = lower("api-gateway.${local.zone_name}")
  content = local.api_gateway_hostname
  type    = "CNAME"
  proxied = true
  ttl     = 1
}
```

Then this fixes all of our diff issues because it also doesn't need to handle the `nulls` being set for the other properties in the response, because there are no no changes.

What you should probably fix in the provider is if `proxied = true` is set and the `type = "CNAME"`. The provider should bail and error on the fact that these two properties cannot bet set in this configuration?

**Comment by ghost** [comment]
Hi @ricohomewood,

The only field in your diff without `(known after apply)` is `flatten_cname`, so I'm suspecting that's the culprit. There is indeed some odd behavior in our API around this field (the false state in particular), and I should have a fix for that out by early next week! (Just saw your edit: the setting being absent for proxied records is unintentional.)

We now have a way to mark generated fields as `Computed: true` and/or `Optional: true` in Terraform, so we'll also do that for some of our fields (such as `comment_modified_on`). Hopefully that solves some more of the issues you brought up here.

**Comment by RafPe** [comment]
> We now have a way to mark generated fields as `Computed: true` and/or `Optional: true` in Terraform, so we'll also do that for some of our fields (such as `comment_modified_on`). Hopefully that solves some more of the issues you brought up here.

This will solve a lot of diffs we are seeing once you add these to the ones controlled by you.  Would that also be available soonish :) ?

**Comment by ghost** [comment]
> Would that also be available soonish :) ?

Hi @RafPe, I've released the OpenAPI schema updates last week and they should find their way into the next Terraform provider release :)

Hope that takes care of some of these diffs for you!

**Comment by RafPe** [comment]
I dont think this is properly resolved yet @jhutchings1 - so closure of this one comes a bit as a surprise. 

Using updated provider now ( 5.7.1 ) and still getting diffs - this is just one of the examples. Happens even after apply of the changes ( more records are still affected 

```
  # cloudflare_dns_record.cname_selector2_domainkey_acme_ai will be updated in-place
  ~ resource "cloudflare_dns_record" "cname_selector2_domainkey_acme_ai" {
      ~ comment_modified_on = "2025-05-10T14:39:35Z" -> (known after apply)
      ~ content             = "selector2-acme-ai._domainkey.acmeco.onmicrosoft.com" -> "selector2-acme-ai._domainkey.acmeCo.onmicrosoft.com"
      ~ created_on          = "2025-05-10T14:34:35Z" -> (known after apply)
        id                  = "a******e"
      ~ meta                = jsonencode({}) -> (known after apply)
      ~ modified_on         = "2025-06-22T08:33:18Z" -> (known after apply)
        name                = "selector2._domainkey.acme.ai"
      ~ proxiable           = false -> (known after apply)
      ~ settings            = {
          ~ flatten_cname = false -> (known after apply)
          + ipv4_only     = (known after apply)
          + ipv6_only     = (known after apply)
        } -> (known after apply)
        tags                = []
      + tags_modified_on    = (known after apply)
        # (5 unchanged attributes hidden)
    }
```

**Comment by ghost** [comment]
@RafPe, that sounds like the same [casing issue](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5517#issuecomment-3062641599) and, unfortunately, my understanding is that this is a missing feature, not a bug. Since v5 is an entirely new version, some differences in functionality are expected. Our team currently doesn't have any way of adding custom code here, and even if we did (like in v4), we couldn't handle all possible types of name normalization within Terraform itself. The best way forward for now (sorry!) is to add `lower()` or, better, to lowercase the input at the source if at all possible. I believe this is something that's being looked into for the future, though.
