### ISSUE TITLE
cloudflare_zero_trust_gateway_certificate issues in V5 provider: tries to delete and recreate cert to update cert on every change + gives error unexpected new value: .in_use: was cty.False, but now cty.True

### ISSUE THREAD

**Issue by anordby** [cloudflare/terraform-provider-cloudflare#5692]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.12.0
on windows_amd64
+ provider registry.terraform.io/clementblaise/age v0.1.1
+ provider registry.terraform.io/cloudflare/cloudflare v5.6.0
+ provider registry.terraform.io/datadog/datadog v3.65.0
+ provider registry.terraform.io/hashicorp/azuread v3.4.0
+ provider registry.terraform.io/hashicorp/azurerm v4.32.0
+ provider registry.terraform.io/hashicorp/hcp v0.107.0
+ provider registry.terraform.io/hashicorp/random v3.7.2
+ provider registry.terraform.io/hashicorp/tfe v0.66.0
+ provider registry.terraform.io/hashicorp/time v0.13.1
+ provider registry.terraform.io/integrations/github v6.6.0

Your version of Terraform is out of date! The latest version
is 1.12.2. You can update by downloading from https://developer.hashicorp.com/terraform/install

### Affected resource(s)

cloudflare_zero_trust_gateway_certificate

### Terraform configuration files

```hcl
resource "cloudflare_zero_trust_gateway_certificate" "moller" {
  account_id           = local.cloudflare.account_ids.moller
  validity_period_days = 1826 // 5 years
}
```

### Link to debug output

https://gist.github.com/anordby/6ba0e04711b3a13c24d065d037575148

### Expected output

No errors and certainly not an update of the recently created certificate in cloudflare_zero_trust_gateway_certificate

### Actual output

Error: Provider produced inconsistent result after apply
When applying changes to cloudflare_zero_trust_gateway_certificate.moller, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .in_use: was cty.False, but now cty.True.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

Plan: https://gist.github.com/anordby/6ba0e04711b3a13c24d065d037575148

Apply: https://gist.github.com/anordby/6add56807a44e8e767f5899f9fa9d332

![Image](https://github.com/user-attachments/assets/2d5783e5-8ac7-447e-a59d-15770a5d2e77)

### Steps to reproduce

Add a cloudflare_zero_trust_gateway_certificate using V5 provider

Watch provider try to update it on every change

If you switch to the cert after creating it provider will also barf about "in_use" value unexpected

**Comment by anordby** [comment]
Related to https://github.com/cloudflare/terraform-provider-cloudflare/issues/5643

**Comment by jhutchings1** [comment]
Thanks for reporting, I've assigned it to the appropriate team to have a look.

**Comment by marksieczkowski** [comment]
I'm encountering this as well

**Comment by rafals26** [comment]
Observing a similar issue where the cause of the looped change is: 
```
~ in_use         = true -> false
```

If I apply:
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudflare_zero_trust_gateway_certificate.terraform_managed_resource_5ebb889e-7809-43ce-9b10-e05ff616310d_0, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an
│ unexpected new value: .in_use: was cty.False, but now cty.True.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Looks like a very similar bug to https://github.com/cloudflare/terraform-provider-cloudflare/issues/5795

**Comment by jhutchings1** [comment]
👋🏻  Hey folks, spoke with the engineer who reported they  made some changes here as part of 5.8.2. 

With this new release you can use terraform to create a gateway certificate with just

```tf
resource "cloudflare_zero_trust_gateway_certificate" "moller" {
     account_id  = "<acc-id>"
     validity_period_days = 1826 // 5 years
} 
 ```

You still have to go to dashboard -> settings -> resources -> certificates and activate the certificate. We are working on adding this to terraform too by next release.

Once the certificate is activated, they can add the certificate id to gateway_settings via

```tf
resource "cloudflare_zero_trust_gateway_settings" "gateway_settings" {  
  account_id = "<accid>"
  settings = {
    activity_log = { enabled = true }
    browser_isolation = {
         non_identity_enabled = false
         url_browser_isolation_enabled = false
    }
    certificate = { id = "975b24c4-aa2f-4ebe-8871-cc2ae3293e50" }
 .....
}
```

cc: @rexscaria

**Comment by rafals26** [comment]
The issue I reported in the comment above (https://github.com/cloudflare/terraform-provider-cloudflare/issues/5692#issuecomment-3131272342) has NOT been fixed in 5.8.2.

**Comment by anordby** [comment]
After adding a ZT gateway cert with cloudflare_zero_trust_gateway_certificate using provider version 5.8.2 and changing to it as the active one, the plan still thinks it needs to modify the certificate for some reason (!):

<img width="1132" height="1082" alt="Image" src="https://github.com/user-attachments/assets/4626548c-d7fc-468a-b3c3-42559665ff89" />

Also the update still fails like previously reported:

<img width="1118" height="458" alt="Image" src="https://github.com/user-attachments/assets/df4bcba8-e090-49c8-b5f4-714e74eface9" />

@jhutchings1

**Comment by pcanham** [comment]
@jhutchings1 / @KaydeeDee

Any chance of re-opening this ticket, i am also facing the same issue what @anordby has reported. in version v5.8.2

**Comment by jhutchings1** [comment]
@rexscaria can you have a look? Thanks!

**Comment by rexscaria** [comment]
I believe the flag `in use` is misunderstood here. It is a read only flag indicating wether the said certificate is in use or not.


Currently this is the lifecycle of a gateway certificate

To create a certificate, use schema
`
resource "cloudflare_zero_trust_gateway_certificate" "new_cert" {
  account_id           = "<accid>"
  validity_period_days = 2826 // 7 years
}

`

Currently we do not have PUT call support to certificate, which means none of the fields in the certificate resource is editable, once created. But marking a certificate in use takes another route.

Before making a certificate useful at gateway, it needs to be marked as [active](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/user-side-certificates/#activate-a-root-certificate). At the moment this can only be done via UI/API, at settings-> resources -> certificates screen (Or use [this](https://developers.cloudflare.com/api/resources/zero_trust/subresources/gateway/subresources/certificates/methods/activate/) api)

We are hoping to offer this step via terraform PUT calls in the future releases.

Once a certificate is activated, they are ready to use in gateway.

To mark a certificate as `in use`, update your gateway configuration setting named, `certificate` with the id of the certificate.
([API link](https://developers.cloudflare.com/api/resources/zero_trust/subresources/gateway/subresources/configurations/models/gateway_configuration_settings/#(schema))))


This should set the certificate as in use. Pls let us know if this works

**Comment by marksieczkowski** [comment]
@rexscaria I'm not trying to change the `in_use` flag.  I created a certificate with Terraform, manually marked it as active in the UI, it was fine for awhile, then Terraform started trying to delete and recreate the certificate based on wanting to update `in_use`

**Comment by rexscaria** [comment]
Ok. We found the root cause of the issue. Which was when certificate is activate and marked as use from the UI, the terraform state was drifting and due to config issue from us, it couldn't save the modified value to the state.

we have fixed this issue in the new release 5.11.0
from this version, you can create certificate with `validity_period_days` and activate and deactivate the certificate directly from terraform with `activate` field.

to mark the certificate as in use, update the gateway `settings -> certificate -> id` right from terraform and everything should work seamlessly.

**Comment by rafals26** [comment]
I confirm that, at least for me, the issue no longer occurs in provider `5.11.0`. 

Thank you!

**Comment by nav7neeet** [comment]
I am still having the same issue in version 5.17.0. Despite setting `activate to true` it does not activate the certificate and the successvie call to use the certificate fails.



```
resource "cloudflare_zero_trust_gateway_certificate" "gateway_certificate" {
  account_id           = var.account_id
  validity_period_days = 365
  activate             = true
}

resource "cloudflare_zero_trust_gateway_settings" "gateway_certificate_settings" {
  account_id = var.account_id
  settings = {

    certificate = {
      id = cloudflare_zero_trust_gateway_certificate.gateway_certificate.id
    }
  }
}
```

> Error
> │ PUT "https://api.cloudflare.com/client/v4/accounts/<cloudflare-account-id>/gateway/configuration": 400 Bad Request {
> │   "result": null,
> │   "success": false,
> │   "errors": [
> │     {
> │       "code": 2133,
> │       "message": "Certificate must have binding status 'available' (previously called 'active') to be enabled for Gateway."
> │     }
> │   ],
> │   "messages": []
> │ }
